### PR TITLE
Python: Update ollama samples

### LINKED ISSUE #6411: Python: [Bug]: ollama_chat_client.py sample passes tools as direct argument to get_response() causing TypeError
### What happened?

The `ollama_chat_client.py` sample passes `tools` as a direct keyword argument to `OllamaChatClient.get_response()`, but the method doesn't accept `tools` directly. It should be passed inside the `options` dict.

### What did you expect to happen?

The sample should run successfully and return the current time using tool calling.

### Steps to reproduce the issue

1. Set `OLLAMA_MODEL=llama3.2`
2. Run: `uv run python/samples/02-agents/providers/ollama/ollama_chat_client.py`
3. See `TypeError`

### Code Sample

Current broken code (lines 43 and 48 in `ollama_chat_client.py`):

```python
# Non-streaming (line 48):
response = await client.get_response(messages, tools=get_time)

# Streaming (line 43):
async for chunk in client.get_response(messages, tools=get_time, stream=True):
```

Should be:

```python
# Non-streaming:
response = await client.get_response(messages, options={"tools": get_time})

# Streaming:
async for chunk in client.get_response(messages, options={"tools": get_time}, stream=True):
```

### Error Messages / Stack Traces

```
TypeError: FunctionInvocationLayer.get_response() got an unexpected keyword argument 'tools'
```

### Affected file

`python/samples/02-agents/providers/ollama/ollama_chat_client.py`

### Environment

- agent-framework version: latest
- Ollama model: llama3.2
- OS: Linux

### Code Sample

```markdown
from agent_framework import Message, tool
from agent_framework.ollama import OllamaChatClient

@tool
def get_time():
    """Get the current time."""
    from datetime import datetime
    return f"The current time is {datetime.now().strftime('%I:%M %p')}."


async def main():
    client = OllamaChatClient()
    messages = [Message(role="user", contents=["What time is it? Use a tool call"])]

    # This raises TypeError:
    response = await client.get_response(messages, tools=get_time)

    # Should be:
    # response = await client.get_response(messages, options={"tools": get_time})
```

### Error Messages / Stack Traces

```markdown

```

### Package Versions

agent-framework version: 1.8.0 agent-framework-ollama version: 1.0.0b260521 - Python version: 3.14 - Ollama model: llama3.2 - OS: Linux

### Python Version

3.14

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alxxdev**
## Summary

Fix `ollama_chat_client.py` sample where `tools` was passed as a direct keyword argument to `OllamaChatClient.get_response()`, causing `TypeError`.

## Problem

`FunctionInvocationLayer.get_response()` does not accept `tools` as a parameter. It should be passed inside the `options` TypedDict (`ChatOptions`). Running the sample raised:

```
TypeError: FunctionInvocationLayer.get_response() got an unexpected keyword argument 'tools'
```

## Fix

Replaced:
```python
client.get_response(messages, tools=get_time)
client.get_response(messages, tools=get_time, stream=True)
```

With:
```python
client.get_response(messages, options={"tools": get_time})
client.get_response(messages, options={"tools": get_time}, stream=True)
```

## Related issue

Closes #6411

## Testing

- Manual: sample now runs without TypeError
- Verified tool calling works with `llama3.2` model and Ollama

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [Contribution Guidelines](https://github.com/microsoft/agent-framework/blob/main/CONTRIBUTING.md)
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] **Is this a breaking change?** If yes, add "[BREAKING]" prefix to the title of the PR.

### CODE REVIEW

**Review by eavanvalkenburg — APPROVED** [review]

**Comment by alxxdev** [comment]
Hi! Just a friendly ping — this PR has been approved by @eavanvalkenburg and all checks (CLA, label) are passing. Could you please merge it when you get a chance?

**Comment by eavanvalkenburg** [comment]
@alxxdev thanks for your help on this, one of my teammates created the same PR and that was already merged, so closing this.
