### PR TITLE
Python: Pin meta core

### LINKED ISSUE #2431: Python: pip install --upgrade --no-cache-dir agent-framework --pre does not install latest agent-framework-core (1.0.0b251120)
When installing agent-framework with --pre into a clean virtual environment, pip does not pull the latest pre-release of agent-framework-core (1.0.0b251120). Specifically, the installed agent-framework does not contain:

1. agent-framework-core: Langfuse observability captures ChatAgent system instructions [#2316](https://github.com/microsoft/agent-framework/pull/2316)￼
2. agent-framework-core: Introducing support for declarative YAML spec [#2002](https://github.com/microsoft/agent-framework/pull/2002)￼

This suggests that the agent-framework meta-package on PyPI is not depending on the latest agent-framework-core pre-release.

## Steps to reproduce

```sh
python3 -m venv .venv
source .venv/bin/activate

pip install --upgrade --no-cache-dir agent-framework --pre

pip show agent-framework-core
```

### Actual Results

pip show agent-framework-core:   

```sh
Name: agent-framework-core
Version: 1.0.0b251114
Summary: Microsoft Agent Framework for building AI Agents with Python. This is the core package that has all the core abstractions and implementations.
Home-page: https://aka.ms/agent-framework
Author: 
Author-email: Microsoft <af-support@microsoft.com>
License: 
Location: /private/tmp/test_agent_framework/.venv/lib/python3.12/site-packages
Requires: azure-identity, mcp, openai, opentelemetry-api, opentelemetry-exporter-otlp-proto-grpc, opentelemetry-sdk, opentelemetry-semantic-conventions-ai, packaging, pydantic, pydantic-settings, typing-extensions
Required-by: agent-framework, agent-framework-a2a, agent-framework-ag-ui, agent-framework-anthropic, agent-framework-azure-ai, agent-framework-copilotstudio, agent-framework-devui, agent-framework-mem0, agent-framework-purview, agent-framework-redis
```

Additionally, verifying the observability code:

```
grep -n "system_instructions" .venv/lib/python3.12/site-packages/agent_framework/observability.py
```

Output:   
```
179:    SYSTEM_INSTRUCTIONS = "gen_ai.system_instructions"
1123:                    system_instructions=getattr(self, "instructions", None),
1192:                    system_instructions=getattr(self, "instructions", None),
1417:    system_instructions: str | list[str] | None = None,
1443:    if system_instructions:
1444:        if not isinstance(system_instructions, list):
1445:            system_instructions = [system_instructions]
1446:        otel_sys_instructions = [{"type": "text", "content": instruction} for instruction in system_instructions]
```

Lines 1123 and 1192 do not include the updated Langfuse observability behavior from [#2316](https://github.com/microsoft/agent-framework/pull/2316)￼ (capturing ChatAgent system instructions as part of the span).

Similarly, features introduced by [#2002](https://github.com/microsoft/agent-framework/pull/2002)￼ (declarative YAML spec support) are not present in this installed version of agent-framework-core.

**Environment**

- OS: macOS
- Python: 3.12 (virtualenv)
- Installation: clean virtual environment, no cached wheels (--no-cache-dir)
- Command: pip install --upgrade --no-cache-dir agent-framework --pre

### PR DESCRIPTION
**Pull request by eavanvalkenburg**
### Motivation and Context

Pin the meta dependency on core to the latest to keep them in sync.
Also fixes mcp update

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [Contribution Guidelines](https://github.com/microsoft/agent-framework/blob/main/CONTRIBUTING.md)
- [x] All unit tests pass, and I have added new tests where possible
- [ ] **Is this a breaking change?** If yes, add "[BREAKING]" prefix to the title of the PR.

### CODE REVIEW

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/README.md">Python Test Coverage</a><details><summary>Python Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>packages/core/agent_framework</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py">_mcp.py</a></td><td>388</td><td>62</td><td>84%</td><td><a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L106">106</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L110">110</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L170">170</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L179">179</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L243">243</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L253-L254">253&ndash;254</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L275">275</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L300">300</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L315">315</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L321">321</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L325">325</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L361">361</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L430">430</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L457">457</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L491-L492">491&ndash;492</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L494-L502">494&ndash;502</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L504-L506">504&ndash;506</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L509-L510">509&ndash;510</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L556">556</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L571">571</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L589">589</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L630">630</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L643">643</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L646-L647">646&ndash;647</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L651">651</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L661">661</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L685">685</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L688-L689">688&ndash;689</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L693">693</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L703">703</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L734">734</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L753">753</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L755">755</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L762-L763">762&ndash;763</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L782">782</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L784">784</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L790-L793">790&ndash;793</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L810-L814">810&ndash;814</a>, <a href="https://github.com/microsoft/agent-framework/blob/387c650c2a1ae2c077b3753de1a8070056fe3f38/packages/core/agent_framework/_mcp.py#L942">942</a></td></tr><tr><td><b>TOTAL</b></td><td><b>15882</b></td><td><b>2416</b></td><td><b>84%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 2276 | 130 :zzz: | 0 :x: | 0 :fire: | 55.553s :stopwatch: |

File: python/pyproject.toml [hunk 1]
```diff
@@ -23,7 +23,7 @@ classifiers = [
   "Typing :: Typed",
 ]
 dependencies = [
-    "agent-framework-core[all]",
+    "agent-framework-core[all]==1.0.0b251120",
```
Comment (dmytrostruk) [inline python/pyproject.toml:26]: So, is it expected to update this version as well when we do the release? When exactly this should be updated, before the release or after the release? 

I was actually thinking about adding some centralized package version if it's possible in Python, because currently when we update all package versions separately and we do that for Azure Functions project, we need additional approval from Azure Functions team. So, we either need to remove the approval requirement, or put package version in one place, so when we update it, we update all the packages at the same time, and this shouldn't trigger the additional required review. 

But with this change, it looks like we are adding more places where we need to update package versions.

**Review by dmytrostruk — APPROVED** [review]

**Review by giles17 — APPROVED** [review]

File: python/pyproject.toml (hunk 1 above)
Comment (eavanvalkenburg) [reply python/pyproject.toml:26]: So you are right that it is a extra piece, but it does something different and that is to ensure that the version of the metapackage and the version of the core package are always aligned, so the three values that should always be updated together are meta version, core version and this core dependency in meta. I believe that over time we will see that other packages are not released en mass, but only when changes have been done and they need a update.

**Comment by thegovind** [comment]
## ⚠️ This PR introduced a breaking change - Documented in #2734 
@eavanvalkenburg @dmytrostruk @giles17 
This PR breaks the ability to import `agent-framework` due to referencing non-existent attributes in the `mcp.types` module.

### Error
```python
AttributeError: module 'mcp.types' has no attribute 'ToolUseContent'
    at agent_framework/_mcp.py:134
```

### Issue
Lines 134-135 reference `types.ToolUseContent` and `types.ToolResultContent`, but these attributes **don't exist in any released version of the `mcp` package**.

https://github.com/microsoft/agent-framework/blob/main/python/packages/core/agent_framework/_mcp.py#L134-L135

```python
| types.ToolUseContent      # ❌ Does not exist in mcp.types
| types.ToolResultContent   # ❌ Does not exist in mcp.types
```

### Verification
Tested with `mcp` versions 1.13.0, 1.19.0, and 1.23.3 - none contain these types.

```bash
$ python -c "import mcp.types as types; print([attr for attr in dir(types) if 'Tool' in attr])"
['CallToolRequest', 'CallToolRequestParams', 'CallToolResult', 'ListToolsRequest', 
 'ListToolsResult', 'Tool', 'ToolAnnotations', 'ToolListChangedNotification', 
 'ToolsCapability']
```

Notice: No `ToolUseContent` or `ToolResultContent`.

### Impact
- **Cannot import** `agent-framework` at all
- Breaks DeepLearning.AI course materials using this package
- Affects version `1.0.0b251204` (current release)

### Reproduction
```python
from agent_framework import ChatMessage  # Fails immediately
```

### Suggested Fix
Could you either:
1. Remove these type references if they're not actually used, or
2. Clarify which version of `mcp` should contain these types, or  
3. Make these types optional with proper type guards?

This is blocking users from using the package entirely. Thanks!

**Comment by eavanvalkenburg** [comment]
@thegovind please make sure to update the mcp package to the latest, then this works again, has nothing to do with this PR, please make sure to create issues for something like this, because a comment on a closed PR is easy to miss!
