### ISSUE TITLE
Python: GroupChatBuilder() function issue

### ISSUE THREAD

**Issue by kishanp102** [microsoft/agent-framework#1771]
When i am using GroupChatBuilder() then it is not working it's throwing error that cannot import name groupchatbuilder from agent_framework

**Comment by moonbox3** [comment]
@kishanp102 what package version are you using? Please run `pip show agent-framework` (or whatever package you have installed - `agent-framework-core`). Please also provide the stack trace.

**Comment by kishanp102** [comment]
Name: agent-framework
Version: 1.0.0b251028

Name: agent-framework-core
Version: 1.0.0b251016

Traceback (most recent call last):
  File "D:\fastapi-mongo-crud\groupchat.py", line 4, in <module>
    from agent_framework import GroupChatBuilder
ImportError: cannot import name 'GroupChatBuilder' from 'agent_framework' (C:\Users\kishan.kamal\AppData\Local\Programs\Python\Python312\Lib\site-packages\agent_framework\__init__.py)

@moonbox3

**Comment by moonbox3** [comment]
GroupChatBuilder was introduced in 1.0.0b251028, as part of agent-framework-core. This is why it can't be found. We've also released a new package: `agent-framework==1.0.0b251104`. 

To make sure the `-core` package is upgraded, please run: 

```
pip install --upgrade agent-framework agent-framework-core
```

**Comment by moonbox3** [comment]
Closing as this is a package upgrade issue. Tested and verified to work with both 1.0.0b251028 and 1.0.0b251104.
