### ISSUE TITLE
Python: [Bug] ImportError: cannot import name 'Content' from 'agent_framework' in durabletask extension

### ISSUE THREAD

**Issue by eldertree777** [microsoft/agent-framework#4249]
### Description

**Describe the bug**

After the recent update to agent-framework (v1.0.0rc1), the agent-framework-durabletask extension is broken. The core library renamed Content to Contents, but the extension still attempts to import the old name.

**To Reproduce**

1. Install agent-framework==1.0.0rc1
2. Install agent-framework-durabletask
3. Run any agent using DurableAgentState

**Affected Files**

- _executors.py
- _durable_agent_state.py
- _entities.py

**Environment:**

- agent-framework version: 1.0.0b260130
- agent-framework-durabletask version: 1.0.0b260130
- Python version: 3.12

### Code Sample

```markdown

```

### Error Messages / Stack Traces

```markdown

```

### Package Versions

agent-framework-1.0.0b260130

### Python Version

Python 3.12.12

**Comment by eavanvalkenburg** [comment]
Please make sure to update both durable task and core to the latest, for durable task the latest is `1.0.0b260219`

**Comment by eldertree777** [comment]
Fixed by updating to version 1.0.0b260219
This issue is resolved after updating agent-framework-durabletask from 1.0.0b260130 to 1.0.0b260219.
